
name: Core Metrics
on:
  schedule: [{cron: "0 */6 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  core-github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Gabriel-Rockson
          template: classic
          base: activity, community, repositories
          config_timezone: Africa/Accra

          # Languages Analysis
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_threshold: 1%
          plugin_languages_sections: most-used
          plugin_languages_colors: github
          plugin_languages_details: percentage

          # Habits Plugin
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_days: 14
          plugin_habits_from: 200

          # IsoCalendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Lines of code changed
          plugin_lines: yes
          plugin_lines_sections: base
          plugin_lines_repositories_limit: 4

          # WakaTime (if you use it)
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_days: 365
          plugin_wakatime_limit: 5
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: gabriel_rockson

          # Notable contributions
          plugin_notable: yes
          plugin_notable_from: organization     # Show notable contributions in organizations
          plugin_notable_types: commit, pull_request

          # Latest posts from your dev.to or medium
          plugin_posts: yes
          plugin_posts_source: dev.to    # or medium
          plugin_posts_limit: 4
          plugin_posts_user: gabrielrockson

          # Coding habits analysis
          plugin_code: yes
          plugin_code_lines: 12
          plugin_code_load: 100
          plugin_code_visibility: public

          # Repository traffic
          plugin_traffic: yes

